/**
 * The worker/fetcher boundary (SPEC.md §8).
 *
 * The fetcher takes a target URL and a trace id, and nothing else. That is the
 * whole input, deliberately: everything a job payload could otherwise reach —
 * a proxy, a bind address, extra headers, a redirect budget, a timeout, a
 * credential — stays in the fetcher's own frozen policy, where a hostile or
 * buggy upstream cannot touch it.
 *
 * Both directions are parsed with Zod. The worker does not trust the fetcher's
 * reply either: the fetcher is the process that handles hostile input, so its
 * output is the least trustworthy thing in the privileged zone.
 *
 * NO PAGE CONTENT CROSSES BACK. The response carries the snapshot id, the
 * status, a hash, two byte counts and a machine reason — identifiers and
 * numbers. The page text itself is written to web_snapshots by the fetcher and
 * read later by the privileged zone, which is the only place allowed to see it
 * (§8). The schema is .strict(), so a field carrying a body could not be added
 * by accident on one side without the other refusing it.
 */
import { z } from 'zod';

/** Bounded because it is a URL from a job, not from a person. */
const MAX_URL_LENGTH = 2_048;

export const fetchRequestSchema = z
  .object({
    /** The company the snapshot belongs to. */
    company_id: z.string().uuid(),
    url: z.string().min(1).max(MAX_URL_LENGTH),
    trace_id: z.string().min(1).max(64),
  })
  .strict();

export type FetchRequest = z.infer<typeof fetchRequestSchema>;

/**
 * What the fetch resolved to, and — just as important — whether asking again
 * could change the answer.
 *
 *   stored            2xx. Text was extracted and written. The only outcome
 *                     that produces research evidence.
 *   robots_disallowed A Disallow matched. The decision is recorded as a
 *                     text-free row; nothing was fetched (§8).
 *   http_error        4xx. The site answered, and the answer is no. Terminal:
 *                     a 403 or a 404 does not become a 200 by asking twice
 *                     more, and asking twice more is three unwanted requests
 *                     at a site that has already refused us. A diagnostic
 *                     row is written with text NULL.
 *   http_unavailable  5xx, or any other status that is neither 2xx nor 4xx.
 *                     No answer was given, so another attempt is legitimate.
 *                     Retryable, and no row is written.
 *   refused           A §8 guard refused the request. Retryable, as before.
 *
 * The terminal/retryable split lives here, in the contract, rather than in the
 * handler: the two sides have to agree on which failures are worth another
 * attempt, and that agreement is the thing a future change is most likely to
 * break quietly.
 */
export const fetchOutcomeSchema = z.enum([
  'stored',
  'robots_disallowed',
  'http_error',
  'http_unavailable',
  'refused',
]);

export type FetchOutcome = z.infer<typeof fetchOutcomeSchema>;

/** Final: this job will not ask for the page again. */
export const TERMINAL_OUTCOMES: readonly FetchOutcome[] = [
  'stored',
  'robots_disallowed',
  'http_error',
];

/** Worth another attempt inside the job's §6 retry budget. */
export const RETRYABLE_OUTCOMES: readonly FetchOutcome[] = [
  'http_unavailable',
  'refused',
];

export function isRetryable(outcome: FetchOutcome): boolean {
  return RETRYABLE_OUTCOMES.includes(outcome);
}

/**
 * The outcomes whose snapshot carries page text, and so may be extracted.
 *
 * One entry today. It is a named list rather than an `=== 'stored'` because
 * Day 4 reads it to decide what to enqueue, and the question "may this row
 * become evidence?" must have exactly one answer in the codebase.
 */
export const EXTRACTABLE_OUTCOMES: readonly FetchOutcome[] = ['stored'];

export const fetchResponseSchema = z
  .object({
    outcome: fetchOutcomeSchema,
    /** Present when outcome is 'stored'. */
    snapshot_id: z.string().uuid().optional(),
    http_status: z.number().int().min(0).max(599).optional(),
    content_hash: z.string().max(64).optional(),
    bytes: z.number().int().min(0).optional(),
    /** Length of the extracted text, never the text itself. */
    text_length: z.number().int().min(0).optional(),
    robots_allowed: z.boolean(),
    final_url: z.string().max(MAX_URL_LENGTH).optional(),
    /**
     * Stable machine reason, safe to log and to branch on.
     *
     * Constrained to a short lower-case token so that it structurally cannot
     * carry page content: hostile HTML has spaces, angle brackets and
     * punctuation, none of which match. Every value the fetcher produces is
     * generated by the guard, never read from a response.
     */
    reason: z
      .string()
      .max(64)
      .regex(/^[a-z0-9_]+$/, 'reason must be a machine token, never free text')
      .optional(),
    trace_id: z.string().max(64),
  })
  .strict()
  .superRefine((response, ctx) => {
    // Only a 2xx fetch has content, so only 'stored' may describe content. A
    // reply that claimed a text_length for a 403 would be rejected at the
    // boundary rather than believed — which is what keeps an error page from
    // ever looking like evidence to the worker.
    if (response.outcome === 'stored') {
      return;
    }
    for (const field of ['content_hash', 'text_length'] as const) {
      if (response[field] !== undefined) {
        ctx.addIssue({
          code: 'custom',
          path: [field],
          message: `${field} is only meaningful for outcome "stored", not "${response.outcome}"`,
        });
      }
    }
  });

export type FetchResponse = z.infer<typeof fetchResponseSchema>;

/** The header the shared secret travels on. */
export const AUTH_HEADER = 'x-fetcher-secret';
